model_name: cnn1d
model_path: ../models/cnn1d

preprocessing:
  split_type: group
  n_splits: 5
  shuffle: True
  random_state: 42
  channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  normalization: global
  flip_probability: 0.
  use_stock_id: True

model:
  in_channels: 16
  out_channels: 512
  use_stock_id: True
  stock_embedding_dims: 16
  alpha: 1.5
  beta: 1.25
  phi: 1

training:
  amp: False
  learning_rate: 0.0005
  betas:
    - 0.9
    - 0.999
  weight_decay: 0
  epochs: 200
  batch_size: 256
  reduce_lr_patience: 5
  reduce_lr_factor: 0.25
  reduce_lr_min: 0.000001
  early_stopping_patience: 20
  num_workers: 16
  random_state: 42
  deterministic_cudnn: True
