model_name: cnn

preprocessing:
  split_type: stratified
  n_splits: 5
  shuffle: True
  random_state: 42

model:
  in_channels: 8
  #input_size: 8
  #hidden_size: 128
  #num_layers: 1

training:
  amp: False
  learning_rate: 0.001
  betas:
    - 0.9
    - 0.999
  weight_decay: 0
  epochs: 25
  batch_size: 256
  early_stopping_patience: 5
  num_workers: 16
  random_state: 42
  deterministic_cudnn: False
