model_name: cnn1d
model_path: ../models/cnn1d_nested
model_type: regular

preprocessing:
  split_type: nested
  n_splits: 5
  shuffle: True
  random_state: 42

model:
  in_channels: 14

training:
  amp: False
  learning_rate: 0.0005
  betas:
    - 0.9
    - 0.999
  weight_decay: 0
  epochs: 200
  batch_size: 32
  reduce_lr_patience: 5
  reduce_lr_factor: 0.25
  reduce_lr_min: 0.000001
  early_stopping_patience: 20
  num_workers: 16
  random_state: 42
  deterministic_cudnn: True
