model_name: resnet

preprocessing:
  split_type: stratified
  n_splits: 5
  shuffle: True
  random_state: 42

model:
  model_name: resnet18d
  pretrained: True
  trainable_backbone: True

training:
  amp: False
  learning_rate: 0.0001
  betas:
    - 0.9
    - 0.999
  weight_decay: 0
  epochs: 25
  batch_size: 256
  early_stopping_patience: 5
  num_workers: 16
  random_state: 42
  deterministic_cudnn: False
