model_name: resnet
model_path: None #../models/cnn1

preprocessing:
  split_type: stratified
  n_splits: 5
  shuffle: True
  random_state: 42

model:
  in_channels: 8
  #out_channels: 1

training:
  amp: False
  learning_rate: 0.0001
  betas:
    - 0.9
    - 0.999
  weight_decay: 0
  epochs: 100
  batch_size: 256
  early_stopping_patience: 10
  num_workers: 16
  random_state: 42
  deterministic_cudnn: False
