model_name: lgb
model_path: ../models/lgb

preprocessing:
  create_features: True
  split_type: group
  n_splits: 5
  shuffle: True
  random_state: 42

predictors:
  - stock_id
  - book_seconds_in_bucket_count
  # Raw book feature aggregations
  - book_bid_size1_std, book_bid_size2_std, book_ask_size1_std, book_ask_size2_std,
  # Book competitiveness aggregations
  - book_bid_price_competitiveness_mean, book_bid_price_competitiveness_max, book_bid_price_competitiveness_distance,
  - book_ask_price_competitiveness_mean, book_ask_price_competitiveness_max, book_ask_price_competitiveness_distance,
  # Book distance aggregations
  - book_bid_ask_price1_distance_mean, book_bid_ask_price1_distance_std, book_bid_ask_price1_distance_max,
  - book_bid_ask_price2_distance_mean, book_bid_ask_price2_distance_std, book_bid_ask_price2_distance_max,
  # Book squared log returns aggregations
  - book_bid_price1_squared_log_returns_mean, book_bid_price1_squared_log_returns_std,
  - book_bid_price2_squared_log_returns_mean, book_bid_price2_squared_log_returns_std,
  - book_ask_price1_squared_log_returns_mean, book_ask_price1_squared_log_returns_std,
  - book_ask_price2_squared_log_returns_mean, book_ask_price2_squared_log_returns_std,
  - book_bid_size1_squared_log_returns_mean, book_bid_size1_squared_log_returns_std,
  - book_bid_size2_squared_log_returns_mean, book_bid_size2_squared_log_returns_std,
  - book_ask_size1_squared_log_returns_mean, book_ask_size1_squared_log_returns_std,
  - book_ask_size2_squared_log_returns_mean, book_ask_size2_squared_log_returns_std,
  # Book weighted average price aggregations
  - book_wap1_std,
  - book_wap1_squared_log_returns_mean, book_wap1_squared_log_returns_std, book_wap1_squared_log_returns_realized_volatility,
  - book_wap2_std,
  - book_wap2_squared_log_returns_mean, book_wap2_squared_log_returns_std, book_wap2_squared_log_returns_realized_volatility,
  - book_wap3_std,
  - book_wap3_squared_log_returns_mean, book_wap3_squared_log_returns_std, book_wap3_squared_log_returns_realized_volatility,
  # Book moving realized volatility aggregations
  - book_wap1_4_second_interval_realized_volatility_mean, book_wap1_4_second_interval_realized_volatility_std,
  - book_wap1_9_second_interval_realized_volatility_mean, book_wap1_9_second_interval_realized_volatility_std,
  - book_wap1_16_second_interval_realized_volatility_mean, book_wap1_16_second_interval_realized_volatility_std,
  - trade_seconds_in_bucket_count,
  # Trade raw feature aggregations
  - trade_price_std, trade_size_std,
  # Trade order average size aggregations
  - trade_order_average_size_mean, trade_order_average_size_std,
  # Trade squared log returns aggregations
  - trade_price_squared_log_returns_mean, trade_price_squared_log_returns_realized_volatility

model:
  num_leaves: 2 ** 7
  learning_rate: 0.01
  bagging_fraction: 0.9
  bagging_freq: 1
  feature_fraction: 0.7
  feature_fraction_bynode: 1
  min_data_in_leaf: 250
  max_bin: 255
  lambda_l1: 0.1
  lambda_l2: 0.5
  max_depth: -1
  seed: 42
  feature_fraction_seed: 42
  bagging_seed: 42
  drop_seed: 42
  data_random_seed: 42
  boosting_type: gbdt
  verbose: 1
  n_jobs: -1

fit:
  boosting_rounds: 5000,
  early_stopping_rounds: 250
  verbose_eval: 500
