model_name: mlp_mixer
model_path: ../models/mlp_mixer

preprocessing:
  create_features: False
  split_type: group
  n_splits: 5
  shuffle: True
  random_state: 42
  channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
  normalization: global
  flip_probability: 0.
  use_stock_id: True

model:
  sequence_length: 600
  channels: 25
  patch_size: (100, 5)
  hidden_dim: 64
  num_blocks: 2
  token_mixer_dim: 64
  token_mixer_dropout_rate: 0
  channel_mixer_dim: 64
  channel_mixer_dropout_rate: 0
  use_stock_id: True
  stock_embedding_dims: 16

training:
  amp: False
  learning_rate: 0.0005
  betas:
    - 0.9
    - 0.999
  weight_decay: 0
  epochs: 200
  batch_size: 256
  reduce_lr_patience: 5
  reduce_lr_factor: 0.25
  reduce_lr_min: 0.000001
  early_stopping_patience: 20
  num_workers: 16
  random_state: 42
  deterministic_cudnn: False
