model_name: rnn
model_path: ../models/rnn_regular
model_type: regular

preprocessing:
  split_type: nested
  n_splits: 5
  shuffle: True
  random_state: 42

model:
  input_size: 16
  hidden_size: 64
  num_layer: 1

training:
  amp: False
  learning_rate: 0.0005
  betas:
    - 0.9
    - 0.999
  weight_decay: 0
  epochs: 200
  batch_size: 256
  reduce_lr_patience: 5
  reduce_lr_factor: 0.25
  reduce_lr_min: 0.000001
  early_stopping_patience: 20
  num_workers: 16
  random_state: 42
  deterministic_cudnn: True
