model_name: rnn
model_path: ../models/cnn1d_regular
model_type: regular

preprocessing:
  split_type: nested
  n_splits: 5
  shuffle: True
  random_state: 42

model:
<<<<<<< HEAD:config.yaml
  in_channels: 14
=======
  in_channels: 16
>>>>>>> eb4bd8653e06f25af7e7106939078960694f6d2c:rnn_config.yaml

training:
  amp: False
  learning_rate: 0.0005
  betas:
    - 0.9
    - 0.999
  weight_decay: 0
  epochs: 200
  batch_size: 32
  reduce_lr_patience: 5
  reduce_lr_factor: 0.25
  reduce_lr_min: 0.000001
  early_stopping_patience: 20
  num_workers: 16
  random_state: 42
  deterministic_cudnn: True
